#!/bin/sh
#
# name     : tmuxen, tmux environment made easy
# author   : Xu Xiaodong <xxdlhy@gmail.com>
# license  : GPL
# created  : 2012 Jul 01
# modified : 2013 Jul 06
#

cmd=$(which tmux)      # tmux path
session=$(hostname -s) # session name

if [ -z $cmd ]; then
    echo "You need to install tmux."
    exit 1
fi

$cmd has-session -t $session 2> /dev/null

if [ $? != 0 ]; then

    $cmd new-session -d -n wat -s $session "zsh -is eval 'cd script;watch ./peek'"
    $cmd new-window     -n xpm -t $session "zsh -is eval 'cd /root/software/xpm/aero/src/primecoinMiner'"
    $cmd new-window     -n run -t $session "zsh -is eval 'cd /root/software/xpm/aero'"
    $cmd split-window -h -p 50 -t $session:1 "zsh"
    $cmd select-window  -t $session:1
    $cmd select-pane    -t $session:1.2
fi

$cmd attach -t $session

exit 0
